# Generated by Django 4.2.6 on 2023-10-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.JSONField()),
                ('published_date', models.CharField(max_length=20)),
                ('isbn_number', models.CharField(max_length=20, unique=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(max_length=20)),
                ('preview_link', models.URLField(max_length=255)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
