# Generated by Django 4.2.6 on 2023-10-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book_list',
            field=models.IntegerField(choices=[(0, 'To Read'), (1, 'Reading'), (2, 'Finish Readong')], default=1),
            preserve_default=False,
        ),
    ]
