# Generated by Django 4.2.6 on 2023-10-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
