# Generated by Django 4.2.6 on 2023-10-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookshow_delete_book'),
        ('book', '0003_remove_book_status'),
    ]

    operations = [
    ]
