# Generated by Django 4.2.6 on 2023-10-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_wishlist_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='book',
        ),
    ]
