# Generated by Django 4.2.6 on 2023-10-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_wishlist_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='book_list',
            field=models.IntegerField(),
        ),
    ]
