# Generated by Django 4.2.6 on 2023-10-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_wishlist_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='book',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('book', 'book_list')},
        ),
    ]
