# Generated by Django 4.2.6 on 2023-10-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_wishlist_book_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
    ]
