# Generated by Django 4.2.6 on 2023-10-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0001_initial'),
        ('user_profile', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dataset.book'),
            preserve_default=False,
        ),
    ]
